# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWyzqmdhq7FV9mQGc8QG-dF8fkBT4Ou_
"""

import pandas as pd
df=pd.read_excel("knn_2d_blobs.xlsx")
print(df.head())

X=df[["x1","x2"]]
y=df["label"]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=2,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled,y_train)

y_pred =knn.predict(X_test_scaled)
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",round(acc,2))

"""from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test,y_pred)
sns.heatmap(cm,annot=True,fmt="d",cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test,y_pred)
sns.heatmap(cm,annot=True,fmt="d",cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

import numpy as np
x_min,x_max=X["x1"].min() - 1,X["x1"].max()+1
y_min,y_max=X["x2"].min() - 1,X["x2"].max()+1
xx,yy=np.meshgrid(np.arange(x_min, x_max, 0.02),np.arange(y_min, y_max, 0.02))
Z= knn.predict(scaler.transform(np.c_[xx.ravel(), yy.ravel()]))
Z =Z.reshape(xx.shape)
plt.figure(figsize=(7,6))
plt.contourf(xx,yy,Z,alpha=0.3,cmap='viridis')
plt.scatter(X["x1"],X["x2"],c=y,cmap='viridis',edgecolor='k')
plt.xlabel("x1")
plt.ylabel("x2")
plt.title("KNN  Decision Boundary(k=5)")
plt.show()

import numpy as np
x_min,x_max=X["x1"].min() - 1,X["x1"].max()+1
y_min,y_max=X["x2"].min() - 1,X["x2"].max()+1
xx,yy=np.meshgrid(np.arange(x_min, x_max, 0.02),np.arange(y_min, y_max, 0.02))
Z= knn.predict(scaler.transform(np.c_[xx.ravel(), yy.ravel()]))
Z =Z.reshape(xx.shape)
plt.figure(figsize=(7,6))
plt.contourf(xx, yy, Z, alpha=0.3,cmap='viridis')
plt.scatter(X["x1"],X["x2"], c=y,cmap='viridis',edgecolor='k')
plt.title("KNN Decision Boundary (K=5)")
plt.xlabel("x1")
plt.ylabel("x2")
plt.show()

new_points = np.array([
    [0.5,-2],
    [-6,5],
    [4,6]])
new_points_scaled=scaler.transform(new_points)
predicted_labels=knn.predict(new_points_scaled)
print("Predicted classes:",predicted_labels)
plt.figure(figsize=(7,6))
plt.scatter(X["x1"],X["x2"],c=y,cmap='viridis',s=40)
label="Training data)"
plt.scatter(new_points[:,0],new_points[:,1],c=predicted_labels,cmap="viridis",edgecolor="black",s=200,marker="+",label="New predictions")
plt.title("KNN Classification with new points(k=5)")
plt.xlabel("x1")
plt.ylabel("x2")
plt.legend
plt.show()

_